version: "3"

services:

  gldemo:
    build: 
      context: .
      args:
        - GID=${MYGID}
        - UID=${MYUID}
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.docker.xauth
    network_mode: "host"
    volumes:
      - ./:/home/contuser/data:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - $HOME/.Xauthority:/root/.Xauthority:rw
    user: "${MYUID}:${MYGID}"
    devices:
      - /dev/dri
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt: 
      - "apparmor:unconfined"